apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: rujfyls/user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_HOST
              value: 192.168.1.58
            - name: spring.mvc.servlet.path
              value: /user-service
            - name: SPRING_ADMIN
              value: http://admin-service/admin-service
